// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCtDoQmKEfIQ_9-NadxySQ7WQWIOqXSo',
    appId: '1:266485954806:web:73c410db687846009214d7',
    messagingSenderId: '266485954806',
    projectId: 'heart-diseases-app',
    authDomain: 'heart-diseases-app.firebaseapp.com',
    storageBucket: 'heart-diseases-app.firebasestorage.app',
    measurementId: 'G-WSMND2Q61V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr70ZzutGmNjwqmm4yudbJcdLgMj_wM8g',
    appId: '1:266485954806:android:0c8f1f992b7a6e8e9214d7',
    messagingSenderId: '266485954806',
    projectId: 'heart-diseases-app',
    storageBucket: 'heart-diseases-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bFLgR9fYAwNpikQbZYoxxCZ9ApOUWqg',
    appId: '1:266485954806:ios:ebaadedc6ce63bbe9214d7',
    messagingSenderId: '266485954806',
    projectId: 'heart-diseases-app',
    storageBucket: 'heart-diseases-app.firebasestorage.app',
    iosBundleId: 'com.example.heartDiseaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bFLgR9fYAwNpikQbZYoxxCZ9ApOUWqg',
    appId: '1:266485954806:ios:ebaadedc6ce63bbe9214d7',
    messagingSenderId: '266485954806',
    projectId: 'heart-diseases-app',
    storageBucket: 'heart-diseases-app.firebasestorage.app',
    iosBundleId: 'com.example.heartDiseaseApp',
  );
}
